In [ ]:
import os
import sys
from pathlib import Path

# Use the notebook folder as working directory so relative paths are portable.
nb_file = globals().get("__vsc_ipynb_file__")
PROJECT_ROOT = Path(nb_file).resolve().parent if nb_file else Path.cwd().resolve()
os.chdir(PROJECT_ROOT)

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print(f"Working directory: {PROJECT_ROOT}")

Hello World?


In [15]:
#Transformer en vecteur de pixel

from PIL import Image
import numpy as np
import os

#example of convertion
# open image
# img = Image.open('Ensemble_B_20/Cercle5/147_Cercle5.png')

# # convert to numpy array
# pixel_matrix = np.asarray(img)

# # convert to 1D
# pixel_vector = pixel_matrix.flatten()

# print(pixel_vector)
# print(pixel_vector.shape)

# creer un dictionnaire des images

#one hot encoding
types = [
    "Cercle2",
    "Cercle5",
    "Diamant2",
    "Diamant5",
    "Hexagone2",
    "Hexagone5",
    "Triangle2",
    "Triangle5",
]

one_hot = {}

for i, img_type in enumerate(types):
    encoding = [0] * len(types)
    encoding[i] = 1
    one_hot[img_type] = tuple(encoding)

#image DBs
path = "Ensemble_B"
image_db = {}

for encoding in one_hot.values():
    image_db[encoding] = []

for image_type in types:

    folder = os.path.join(path, image_type)

    encoding = one_hot[image_type]

    for filename in os.listdir(folder):

        if filename.endswith(".png"):
            
            img_path = os.path.join(folder, filename)
            img = Image.open(img_path)

            pixel_matrix = np.asarray(img)
            pixel_vector = pixel_matrix.flatten()
            
            image_db[encoding].append(pixel_vector)

#check
for key, value in image_db.items():
    print(key, ":", len(value))
print(image_db[(0,1,0,0,0,0,0,0)][1]);

path_20 = "Ensemble_B_20"
image_db_20 = {}

for encoding in one_hot.values():
    image_db_20[encoding] = []

for image_type in types:

    folder = os.path.join(path_20, image_type)

    encoding = one_hot[image_type]

    for filename in os.listdir(folder):

        if filename.endswith(".png"):
            
            img_path = os.path.join(folder, filename)
            img = Image.open(img_path)

            pixel_matrix = np.asarray(img)
            pixel_vector = pixel_matrix.flatten()
            
            image_db_20[encoding].append(pixel_vector)


#check
for key, value in image_db_20.items():
    print(key, ":", len(value))
print(image_db_20[(0,1,0,0,0,0,0,0)][1]);

[158 140  98 ...  56  91 111]
(1600,)
(1, 0, 0, 0, 0, 0, 0, 0) : 1100
(0, 1, 0, 0, 0, 0, 0, 0) : 544
(0, 0, 1, 0, 0, 0, 0, 0) : 483
(0, 0, 0, 1, 0, 0, 0, 0) : 328
(0, 0, 0, 0, 1, 0, 0, 0) : 1025
(0, 0, 0, 0, 0, 1, 0, 0) : 630
(0, 0, 0, 0, 0, 0, 1, 0) : 976
(0, 0, 0, 0, 0, 0, 0, 1) : 599
[156 159 163 ... 129 126 125]
(1, 0, 0, 0, 0, 0, 0, 0) : 20
(0, 1, 0, 0, 0, 0, 0, 0) : 20
(0, 0, 1, 0, 0, 0, 0, 0) : 20
(0, 0, 0, 1, 0, 0, 0, 0) : 20
(0, 0, 0, 0, 1, 0, 0, 0) : 20
(0, 0, 0, 0, 0, 1, 0, 0) : 20
(0, 0, 0, 0, 0, 0, 1, 0) : 20
(0, 0, 0, 0, 0, 0, 0, 1) : 20
[158 140  98 ...  56  91 111]
